export const PROVINCE_SLUGS = [
    "western",
    "central",
    "southern",
    "northern",
    "eastern",
    "north-western",
    "north-central",
    "uva",
    "sabaragamuwa"
];

export const DISTRICT_SLUGS = [
    "colombo",
    "gampaha",
    "kalutara",
    "kandy",
    "matale",
    "nuwara-eliya",
    "galle",
    "matara",
    "hambantota",
    "jaffna",
    "kilinochchi",
    "mannar",
    "mullaitivu",
    "vavuniya",
    "batticaloa",
    "ampara",
    "trincomalee",
    "kurunegala",
    "puttalam",
    "anuradhapura",
    "polonnaruwa",
    "badulla",
    "monaragala",
    "ratnapura",
    "kegalle"
];